development:
  adapter: postgresql
  encoding: unicode
  database: datadrop_development
  pool: 5
  username: postgres
  password: root
  host: localhost
 
test:
  adapter: postgresql
  encoding: unicode
  database: datadrop_test
  pool: 5
  username: postgres 
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: datadrop_production
  pool: 5
  username: postgres
  password: root
  host: localhost